name: Baidouars
author: SuperMaxime38
version: 0.9.1
main: maxetkita.bedwars.Bedwars
description: INCROYABLE PLUGIN DE BEDWARS DEV PAR MAXIME
api-version: 1.13
commands:
  bedwars:
    aliases: [bw, baidouars]
    permission: bw.command.bw
    description: Admin main command
    
  bwteam:
    aliases: [bwt]
    description : Team command
  
  bwdebug:
    description : Dev command dont use
    permission: bw.command.debug